name: Bug Report
description: Create a report to help us improve
labels: [bug, triage]
body:
- type: markdown
  attributes:
    value: |      
      > Please search to see if an issue already exists for the bug you encountered.
      
      Thanks for taking the time to fill out this bug report!
- type: textarea
  id: bug-description
  attributes:
    label: Describe the bug
    description: A clear and concise description of what the bug is.
    placeholder: Description...
  validations:
    required: true
- type: textarea
  id: reproduction-steps
  attributes:
    label: Reproduction steps
    description: Steps to reproduce the behavior. Please walk us through it step by step.
    placeholder: |
      1. In this environment...
      2. With this config...
      3. Run '...'
      4. See error...
- type: textarea
  attributes:
    label: Aditional info
    description: |
      Links? References? Anything that will give us more context about the issue you are encountering!

      Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
  validations:
    required: false
- type: textarea
  id: logs
  attributes:
    label: Relevant log output
    description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
    render: shell
- type: checkboxes
  id: terms
  attributes:
    description: By submitting this issue, you agree to follow our [Code of Conduct](../../CODE_OF_CONDUCT.md)
    options:
      - label: I agree to follow this project's Code of Conduct
        required: true
