name: Draft Release
on:
  workflow_dispatch:
    # Enable manual workflow run
    inputs:
      tags:
        description: 'Test scenario tags' 
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - "v*" # Push events that match "*". For example: "1.0", "20.15.10"

jobs:
  build:
    name: Create build
    runs-on: ubuntu-20.04
    steps:
      # Upload the build.
      - name: Get release tag version
        run: echo "RELEASE_TAG=${GITHUB_REF#refs/tags/*}" >> $GITHUB_ENV
      - run: echo $RELEASE_TAG
